// Stub binaries embedded as byte arrays. This file is regenerated by
// build\embed_stub.cmd from loader\stub_x64.bin / stub_x86.bin after the
// loader project builds. Stage-1 placeholder values let the generator link
// before the loader has been built once.
#include <stdint.h>

const unsigned char stub_x64_bin[] = { 0xC3 }; // ret
const unsigned int  stub_x64_bin_len = 1;

const unsigned char stub_x86_bin[] = { 0xC3 }; // ret
const unsigned int  stub_x86_bin_len = 1;
