# Reads two binary blobs and writes them as C byte arrays into ${OUT}.
# Invoked at build time from the top-level CMakeLists.txt.
#
# Inputs (passed via -D): OUT, X64, X86

file(READ "${X64}" X64_HEX HEX)
file(READ "${X86}" X86_HEX HEX)

string(LENGTH "${X64_HEX}" X64_HEX_LEN)
string(LENGTH "${X86_HEX}" X86_HEX_LEN)
math(EXPR X64_LEN "${X64_HEX_LEN} / 2")
math(EXPR X86_LEN "${X86_HEX_LEN} / 2")

string(REGEX REPLACE "(..)" "0x\\1," X64_C "${X64_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," X86_C "${X86_HEX}")

file(WRITE "${OUT}"
"// Auto-generated by cmake/gen_embed.cmake. Do not edit.\n"
"#include <stdint.h>\n"
"\n"
"const unsigned char stub_x64_bin[] = { ${X64_C} };\n"
"const unsigned int  stub_x64_bin_len = ${X64_LEN};\n"
"\n"
"const unsigned char stub_x86_bin[] = { ${X86_C} };\n"
"const unsigned int  stub_x86_bin_len = ${X86_LEN};\n"
)
