/* Co2H feature flags -- generated by gen_for_kit.bat */
#define CO2H_SW4_FEATURE_FLAGS
#define SW4_HAS_UNHOOK    1
#define SW4_HAS_ETW       1
#define SW4_HAS_AMSI      1
#define SW4_HAS_ANTIDEBUG 1
#define SW4_HAS_SLEEP_ENC 1

/*
 * SW4Syscalls.h -- generated by SysWhispers4
 * DO NOT EDIT -- regenerate with syswhispers.py
 */
#pragma once
#ifndef SW4_SYSCALLS_H
#define SW4_SYSCALLS_H

#include "SW4Syscalls_Types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 *  Runtime initialization
 *  Hell's Gate  -- reads SSN from ntdll stub opcode
 * ========================================================================= */
EXTERN_C BOOL SW4_Initialize(VOID);

EXTERN_C BOOL SW4_PatchEtw(VOID);   /* Optionally patch user-mode ETW writer */
EXTERN_C BOOL SW4_PatchAmsi(VOID);  /* Patch AmsiScanBuffer */
EXTERN_C BOOL SW4_UnhookNtdll(VOID); /* Remap clean ntdll .text section */
EXTERN_C BOOL SW4_AntiDebugCheck(VOID); /* Check for debugger presence */
EXTERN_C VOID SW4_SleepEncrypt(DWORD dwMilliseconds); /* Sleep with memory encryption */

/* =========================================================================
 *  Syscall function prototypes
 * ========================================================================= */
EXTERN_C NTSTATUS NTAPI SW4_NtCreateThreadEx(PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle, PVOID StartRoutine, PVOID Argument, ULONG CreateFlags, SIZE_T ZeroBits, SIZE_T StackSize, SIZE_T MaximumStackSize, PPS_ATTRIBUTE_LIST AttributeList);
EXTERN_C NTSTATUS NTAPI SW4_NtWaitForSingleObject(HANDLE Handle, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
EXTERN_C NTSTATUS NTAPI SW4_NtFreeVirtualMemory(HANDLE ProcessHandle, PVOID* BaseAddress, PSIZE_T RegionSize, ULONG FreeType);
EXTERN_C NTSTATUS NTAPI SW4_NtWriteVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToWrite, PSIZE_T NumberOfBytesWritten);
EXTERN_C NTSTATUS NTAPI SW4_NtAllocateVirtualMemory(HANDLE ProcessHandle, PVOID* BaseAddress, ULONG_PTR ZeroBits, PSIZE_T RegionSize, ULONG AllocationType, ULONG Protect);
EXTERN_C NTSTATUS NTAPI SW4_NtResumeThread(HANDLE ThreadHandle, PULONG SuspendCount);
EXTERN_C NTSTATUS NTAPI SW4_NtGetContextThread(HANDLE ThreadHandle, PCONTEXT ThreadContext);
EXTERN_C NTSTATUS NTAPI SW4_NtCreateSection(PHANDLE SectionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PLARGE_INTEGER MaximumSize, ULONG SectionPageProtection, ULONG AllocationAttributes, HANDLE FileHandle);
EXTERN_C NTSTATUS NTAPI SW4_NtOpenProcess(PHANDLE ProcessHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PCLIENT_ID ClientId);
EXTERN_C NTSTATUS NTAPI SW4_NtTerminateProcess(HANDLE ProcessHandle, NTSTATUS ExitStatus);
EXTERN_C NTSTATUS NTAPI SW4_NtUnmapViewOfSection(HANDLE ProcessHandle, PVOID BaseAddress);
EXTERN_C NTSTATUS NTAPI SW4_NtReadVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToRead, PSIZE_T NumberOfBytesRead);
EXTERN_C NTSTATUS NTAPI SW4_NtOpenSection(PHANDLE SectionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
EXTERN_C NTSTATUS NTAPI SW4_NtQueryInformationProcess(HANDLE ProcessHandle, PROCESSINFOCLASS ProcessInformationClass, PVOID ProcessInformation, ULONG ProcessInformationLength, PULONG ReturnLength);
EXTERN_C NTSTATUS NTAPI SW4_NtProtectVirtualMemory(HANDLE ProcessHandle, PVOID* BaseAddress, PSIZE_T RegionSize, ULONG NewProtect, PULONG OldProtect);
EXTERN_C NTSTATUS NTAPI SW4_NtSetContextThread(HANDLE ThreadHandle, PCONTEXT ThreadContext);
EXTERN_C NTSTATUS NTAPI SW4_NtClose(HANDLE Handle);
EXTERN_C NTSTATUS NTAPI SW4_NtQueueApcThread(HANDLE ThreadHandle, PPS_APC_ROUTINE ApcRoutine, PVOID ApcArgument1, PVOID ApcArgument2, PVOID ApcArgument3);
EXTERN_C NTSTATUS NTAPI SW4_NtMapViewOfSection(HANDLE SectionHandle, HANDLE ProcessHandle, PVOID* BaseAddress, ULONG_PTR ZeroBits, SIZE_T CommitSize, PLARGE_INTEGER SectionOffset, PSIZE_T ViewSize, SECTION_INHERIT InheritDisposition, ULONG AllocationType, ULONG Win32Protect);

#ifdef __cplusplus
}
#endif

#endif /* SW4_SYSCALLS_H */
